### ISSUE TITLE
RecursionError calling get_converter() on Python 3.7.1

### ISSUE THREAD

**Issue by pschanely** [microsoft/lsprotocol#136]
Hi folks. Thanks for this project! Excited to try out pygls 1.0 on top of lsprotocol.
I noticed the following RecursionError; not sure whether you want to try to work around it, or just bump the minimum supported version. (either is OK by me)

```
$ python
Python 3.7.1 (default, Dec 18 2022, 11:28:25) 
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from lsprotocol.converters import get_converter
>>> get_converter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lsprotocol/converters.py", line 17, in get_converter
    return _hooks.register_hooks(converter)
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lsprotocol/_hooks.py", line 35, in register_hooks
    _resolve_forward_references()
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lsprotocol/_hooks.py", line 30, in _resolve_forward_references
    attrs.resolve_types(value, lsp_types.ALL_TYPES_MAP, {})
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/site-packages/attr/_funcs.py", line 410, in resolve_types
    hints = typing.get_type_hints(cls, globalns=globalns, localns=localns)
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 973, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 262, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 262, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 263, in _eval_type
    if ev_args == t.__args__:
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 658, in __eq__
    return frozenset(self.__args__) == frozenset(other.__args__)
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 664, in __hash__
  [... repeats many times ...]
  File "/Users/pschanely/.pyenv/versions/3.7.1/lib/python3.7/typing.py", line 477, in __hash__
    return hash((self.__forward_arg__, self.__forward_value__))
RecursionError: maximum recursion depth exceeded
```

**Comment by brettcannon** [comment]
Does this happen with a newer version of Python? Just trying to narrow down if this is from our code, `typing`, or `attrs`. Since the `__hash__` isn't by us and that's where the recursion is, my guess is Python 3.7 might be the problem.
